name: Deploy Static Website to Production

on:
  push:
    branches: [oracle-production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: oracle-production
      - name: install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.1'
      - name: install npm dependencies
        run: npm install
      - name: build task
        run: npm run build:production
      - name: copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USER }}
          PORT: ${{ secrets.DEPLOY_PORT }}
          KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          source: 'dist/'
          target: ${{ secrets.DEPLOY_ORACLE }}/production
          strip_components: 1
      - name: executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USER }}
          PORT: ${{ secrets.DEPLOY_PORT }}
          KEY: ${{ secrets.DEPLOY_KEY }}
          script: |
            systemctl restart nginx
